-- Chinese product name translations (259 products)
-- Run: psql -U postgres -d b2b_o2o -f translate_products_zh.sql

BEGIN;

UPDATE products SET name_zh = '汰渍洗衣粉 1千克' WHERE id = 1;
UPDATE products SET name_zh = '卫宝香皂 90克' WHERE id = 2;
UPDATE products SET name_zh = 'Tarang奶粉 1千克' WHERE id = 3;
UPDATE products SET name_zh = 'Olpers奶油 200毫升' WHERE id = 4;
UPDATE products SET name_zh = '雀巢纯净水 1.5升' WHERE id = 5;
UPDATE products SET name_zh = 'Pakola芒果饮料 250毫升' WHERE id = 6;
UPDATE products SET name_zh = '乐事马萨拉薯片 34克' WHERE id = 7;
UPDATE products SET name_zh = '家乐方便面 66克' WHERE id = 8;
UPDATE products SET name_zh = '夏士莲洗发水 185毫升' WHERE id = 9;
UPDATE products SET name_zh = 'National大米 5千克' WHERE id = 10;
UPDATE products SET name_zh = '汰渍洗衣粉 500克' WHERE id = 11;
UPDATE products SET name_zh = '碧浪洗衣粉 1千克' WHERE id = 12;
UPDATE products SET name_zh = 'Vim洗碗皂 200克' WHERE id = 13;
UPDATE products SET name_zh = '亮净马桶清洁剂 500毫升' WHERE id = 14;
UPDATE products SET name_zh = 'Domex地板清洁剂 500毫升' WHERE id = 15;
UPDATE products SET name_zh = '舒肤佳抗菌香皂 130克' WHERE id = 16;
UPDATE products SET name_zh = '滴露香皂 115克' WHERE id = 17;
UPDATE products SET name_zh = 'Comfort衣物柔顺剂 450毫升' WHERE id = 18;
UPDATE products SET name_zh = 'Tarang奶粉 500克' WHERE id = 19;
UPDATE products SET name_zh = 'Olpers全脂牛奶 1升' WHERE id = 20;
UPDATE products SET name_zh = '雀巢纯净水 500毫升' WHERE id = 21;
UPDATE products SET name_zh = 'Haleeb全脂牛奶 1升' WHERE id = 22;
UPDATE products SET name_zh = 'Rooh Afza糖浆 800毫升' WHERE id = 23;
UPDATE products SET name_zh = 'Dews菠萝汁 1升' WHERE id = 24;
UPDATE products SET name_zh = '百事可乐 500毫升瓶装' WHERE id = 25;
UPDATE products SET name_zh = '可口可乐 500毫升瓶装' WHERE id = 26;
UPDATE products SET name_zh = '七喜 500毫升瓶装' WHERE id = 27;
UPDATE products SET name_zh = '雪碧 345毫升罐装' WHERE id = 28;
UPDATE products SET name_zh = '激浪 500毫升' WHERE id = 29;
UPDATE products SET name_zh = '芬达橙味 345毫升罐装' WHERE id = 30;
UPDATE products SET name_zh = '红牛能量饮料 250毫升' WHERE id = 31;
UPDATE products SET name_zh = '蜇人能量饮料 250毫升' WHERE id = 32;
UPDATE products SET name_zh = '立顿黄牌茶包 100袋' WHERE id = 33;
UPDATE products SET name_zh = '立顿黄牌散茶 200克' WHERE id = 34;
UPDATE products SET name_zh = 'Tapal散茶 200克' WHERE id = 35;
UPDATE products SET name_zh = 'Tapal散茶 500克' WHERE id = 36;
UPDATE products SET name_zh = '雀巢经典咖啡 200克' WHERE id = 37;
UPDATE products SET name_zh = '雀巢三合一原味咖啡 10包' WHERE id = 38;
UPDATE products SET name_zh = 'Brooke Bond至尊茶叶 200克' WHERE id = 39;
UPDATE products SET name_zh = '乐事经典原味薯片 34克' WHERE id = 40;
UPDATE products SET name_zh = '家乐蔬菜方便面 66克' WHERE id = 41;
UPDATE products SET name_zh = 'Cocomo巧克力威化 18克' WHERE id = 42;
UPDATE products SET name_zh = '品客酸奶油薯片 107克' WHERE id = 43;
UPDATE products SET name_zh = '奇多玉米泡芙 27克' WHERE id = 44;
UPDATE products SET name_zh = '印尼干炒方便面 80克' WHERE id = 45;
UPDATE products SET name_zh = '奥利奥巧克力夹心饼干 137克' WHERE id = 46;
UPDATE products SET name_zh = 'Peek Freans玛丽饼干 130克' WHERE id = 47;
UPDATE products SET name_zh = 'Sooper饼干 180克' WHERE id = 48;
UPDATE products SET name_zh = '奇巧牛奶巧克力 40克' WHERE id = 49;
UPDATE products SET name_zh = '吉百利全脂牛奶巧克力 38克' WHERE id = 50;
UPDATE products SET name_zh = '瑞士三角牛奶巧克力 100克' WHERE id = 51;
UPDATE products SET name_zh = 'Candy Land果冻 20克' WHERE id = 52;
UPDATE products SET name_zh = 'Dalda植物酥油 1千克' WHERE id = 53;
UPDATE products SET name_zh = 'Dalda植物酥油 2千克' WHERE id = 54;
UPDATE products SET name_zh = 'Habib食用油 3升' WHERE id = 55;
UPDATE products SET name_zh = 'Soya Supreme食用油 5升' WHERE id = 56;
UPDATE products SET name_zh = 'Golden Deski纯酥油 1千克' WHERE id = 57;
UPDATE products SET name_zh = 'Canola Gold菜籽油 3升' WHERE id = 58;
UPDATE products SET name_zh = 'National红辣椒粉 100克' WHERE id = 59;
UPDATE products SET name_zh = 'Shan香饭香料 50克' WHERE id = 60;
UPDATE products SET name_zh = 'Shan哈利姆香料 50克' WHERE id = 61;
UPDATE products SET name_zh = 'National番茄酱 800克' WHERE id = 62;
UPDATE products SET name_zh = 'National恰特香料 50克' WHERE id = 63;
UPDATE products SET name_zh = '家乐鸡精块 24粒' WHERE id = 64;
UPDATE products SET name_zh = 'National香米 1千克' WHERE id = 65;
UPDATE products SET name_zh = 'Shakarganj白糖 1千克' WHERE id = 66;
UPDATE products SET name_zh = 'Shakarganj白糖 5千克' WHERE id = 67;
UPDATE products SET name_zh = 'Pilsbury全麦面粉 5千克' WHERE id = 68;
UPDATE products SET name_zh = 'National加碘盐 1千克' WHERE id = 69;
UPDATE products SET name_zh = '去皮绿豆 500克' WHERE id = 70;
UPDATE products SET name_zh = '红扁豆 500克' WHERE id = 71;
UPDATE products SET name_zh = '夏士莲洗发水 350毫升' WHERE id = 72;
UPDATE products SET name_zh = '多芬深层修复洗发水 360毫升' WHERE id = 73;
UPDATE products SET name_zh = '海飞丝经典去屑洗发水 360毫升' WHERE id = 74;
UPDATE products SET name_zh = '卫宝沐浴露 250毫升' WHERE id = 75;
UPDATE products SET name_zh = '多芬清爽沐浴露 250毫升' WHERE id = 76;
UPDATE products SET name_zh = '旁氏冷霜 200克' WHERE id = 77;
UPDATE products SET name_zh = '光彩亮丽面霜 75克' WHERE id = 78;
UPDATE products SET name_zh = '妮维雅经典铁罐润肤霜 150毫升' WHERE id = 79;
UPDATE products SET name_zh = '潘婷护发素 360毫升' WHERE id = 80;
UPDATE products SET name_zh = '夏士莲护发素 300毫升' WHERE id = 81;
UPDATE products SET name_zh = 'Vatika椰子发油 200毫升' WHERE id = 82;
UPDATE products SET name_zh = 'Bio Amla发油 200毫升' WHERE id = 83;
UPDATE products SET name_zh = '高露洁全面防护牙膏 150克' WHERE id = 84;
UPDATE products SET name_zh = '高露洁牙膏 75克' WHERE id = 85;
UPDATE products SET name_zh = '舒适达美白牙膏 75克' WHERE id = 86;
UPDATE products SET name_zh = '洁诺抗菌牙膏 175克' WHERE id = 87;
UPDATE products SET name_zh = '李施德林清凉薄荷漱口水 250毫升' WHERE id = 88;
UPDATE products SET name_zh = '高露洁中毛牙刷' WHERE id = 89;
UPDATE products SET name_zh = '帮宝适新生儿纸尿裤 42片' WHERE id = 90;
UPDATE products SET name_zh = '帮宝适婴儿干爽纸尿裤3号 40片' WHERE id = 91;
UPDATE products SET name_zh = '好奇3号拉拉裤 44片' WHERE id = 92;
UPDATE products SET name_zh = '强生婴儿洗发水 200毫升' WHERE id = 93;
UPDATE products SET name_zh = '强生婴儿润肤露 200毫升' WHERE id = 94;
UPDATE products SET name_zh = '雀巢米粉 250克' WHERE id = 95;
UPDATE products SET name_zh = 'Odonil卫生间空气清新剂 75克' WHERE id = 96;
UPDATE products SET name_zh = '灭害灵速效杀虫气雾剂 600毫升' WHERE id = 97;
UPDATE products SET name_zh = '灭害灵蚊香 10卷' WHERE id = 98;
UPDATE products SET name_zh = '百洁布3片装' WHERE id = 99;
UPDATE products SET name_zh = 'Saffron抽纸 150张' WHERE id = 100;
UPDATE products SET name_zh = '舒洁湿纸巾 80片' WHERE id = 101;
UPDATE products SET name_zh = 'K&NS炸鸡块 1千克' WHERE id = 102;
UPDATE products SET name_zh = 'K&NS鸡肉块 500克' WHERE id = 103;
UPDATE products SET name_zh = 'K&NS鸡肉条 500克' WHERE id = 104;
UPDATE products SET name_zh = 'Omore Lusso冰淇淋 1升' WHERE id = 105;
UPDATE products SET name_zh = 'Polka巧克力冰淇淋 1升' WHERE id = 106;
UPDATE products SET name_zh = '汰渍洗衣粉 2千克' WHERE id = 107;
UPDATE products SET name_zh = 'Rin洗衣粉 1千克' WHERE id = 108;
UPDATE products SET name_zh = '碧浪洗衣粉 500克' WHERE id = 109;
UPDATE products SET name_zh = 'Bonux洗衣粉 1千克' WHERE id = 110;
UPDATE products SET name_zh = '滴露消毒液 200毫升' WHERE id = 111;
UPDATE products SET name_zh = '沙蔓消毒液 500毫升' WHERE id = 112;
UPDATE products SET name_zh = 'Wheel洗衣膏 200克' WHERE id = 113;
UPDATE products SET name_zh = 'Supernet洗衣粉 300克' WHERE id = 114;
UPDATE products SET name_zh = 'Brite荧光增白剂 100克' WHERE id = 115;
UPDATE products SET name_zh = '亮净水箱清洁块 50克' WHERE id = 116;
UPDATE products SET name_zh = 'Pledge家具上光剂 300毫升' WHERE id = 117;
UPDATE products SET name_zh = 'Prestige洗洁精 1升' WHERE id = 118;
UPDATE products SET name_zh = '碧浪原味洗洁精 500毫升' WHERE id = 119;
UPDATE products SET name_zh = 'Olpers低脂牛奶 1升' WHERE id = 120;
UPDATE products SET name_zh = 'Good Milk超高温全脂牛奶 1升' WHERE id = 121;
UPDATE products SET name_zh = '雀巢水果酸奶 400克' WHERE id = 122;
UPDATE products SET name_zh = 'Gourmet酸奶 400克' WHERE id = 123;
UPDATE products SET name_zh = 'Country无盐黄油 200克' WHERE id = 124;
UPDATE products SET name_zh = 'Nurpur加工芝士 500克' WHERE id = 125;
UPDATE products SET name_zh = 'Tarang奶粉 250克' WHERE id = 126;
UPDATE products SET name_zh = '雀巢日常奶精 400克' WHERE id = 127;
UPDATE products SET name_zh = 'Shezan芒果汁 250毫升' WHERE id = 128;
UPDATE products SET name_zh = 'Shezan苹果汁 250毫升' WHERE id = 129;
UPDATE products SET name_zh = 'Maaza芒果饮料 1升' WHERE id = 130;
UPDATE products SET name_zh = '美汁源果粒橙 1升' WHERE id = 131;
UPDATE products SET name_zh = '百事可乐 1.5升瓶装' WHERE id = 132;
UPDATE products SET name_zh = '可口可乐 1.5升瓶装' WHERE id = 133;
UPDATE products SET name_zh = '七喜 1.5升瓶装' WHERE id = 134;
UPDATE products SET name_zh = '雪碧 1.5升瓶装' WHERE id = 135;
UPDATE products SET name_zh = '百事可乐罐装 330毫升' WHERE id = 136;
UPDATE products SET name_zh = '可口可乐罐装 330毫升' WHERE id = 137;
UPDATE products SET name_zh = '激浪罐装 330毫升' WHERE id = 138;
UPDATE products SET name_zh = '美年达橙味 345毫升罐装' WHERE id = 139;
UPDATE products SET name_zh = '百事可乐迷你罐 250毫升' WHERE id = 140;
UPDATE products SET name_zh = '蜇人红色能量饮料 250毫升' WHERE id = 141;
UPDATE products SET name_zh = '纯果乐橙汁 1升' WHERE id = 142;
UPDATE products SET name_zh = '雀巢果维多 250毫升' WHERE id = 143;
UPDATE products SET name_zh = '立顿散茶 100克' WHERE id = 144;
UPDATE products SET name_zh = 'Vital茶叶袋装 500克' WHERE id = 145;
UPDATE products SET name_zh = 'Tapal家庭混合茶 200克' WHERE id = 146;
UPDATE products SET name_zh = '雀巢金牌混合咖啡 100克' WHERE id = 147;
UPDATE products SET name_zh = '大卫杜夫浓缩咖啡57 90克' WHERE id = 148;
UPDATE products SET name_zh = '帝码锡兰茶 100袋' WHERE id = 149;
UPDATE products SET name_zh = '泰特利绿茶 25袋' WHERE id = 150;
UPDATE products SET name_zh = 'Akbar金牌优质茶叶 200克' WHERE id = 151;
UPDATE products SET name_zh = '乐事烧烤味薯片 34克' WHERE id = 152;
UPDATE products SET name_zh = 'Kurkure马萨拉脆条 62克' WHERE id = 153;
UPDATE products SET name_zh = '品客原味薯片 107克' WHERE id = 154;
UPDATE products SET name_zh = '多力多滋奶酪玉米片 73克' WHERE id = 155;
UPDATE products SET name_zh = '家乐虾味方便面 66克' WHERE id = 156;
UPDATE products SET name_zh = '美极马萨拉方便面 70克' WHERE id = 157;
UPDATE products SET name_zh = 'Sunfeast方便面 70克' WHERE id = 158;
UPDATE products SET name_zh = 'Cornnetto烤玉米 50克' WHERE id = 159;
UPDATE products SET name_zh = 'Bisconni可可饼干 60克' WHERE id = 160;
UPDATE products SET name_zh = 'Safeway洋葱圈 60克' WHERE id = 161;
UPDATE products SET name_zh = '奥利奥双层奶油夹心 150克' WHERE id = 162;
UPDATE products SET name_zh = 'Peek Freans捉迷藏饼干 100克' WHERE id = 163;
UPDATE products SET name_zh = 'Bisconni Sooper饼干 130克' WHERE id = 164;
UPDATE products SET name_zh = 'Maliban牛奶酥饼 180克' WHERE id = 165;
UPDATE products SET name_zh = '麦维他消化饼干 200克' WHERE id = 166;
UPDATE products SET name_zh = '奇巧大块巧克力 40克' WHERE id = 167;
UPDATE products SET name_zh = '士力架 50克' WHERE id = 168;
UPDATE products SET name_zh = '赏心牛奶巧克力 57克' WHERE id = 169;
UPDATE products SET name_zh = '特趣焦糖饼干 50克' WHERE id = 170;
UPDATE products SET name_zh = 'Galaxy丝滑牛奶巧克力 42克' WHERE id = 171;
UPDATE products SET name_zh = 'Patchi黑巧克力 100克' WHERE id = 172;
UPDATE products SET name_zh = '哈瑞宝金熊软糖 100克' WHERE id = 173;
UPDATE products SET name_zh = '曼妥思水果味软糖 37克' WHERE id = 174;
UPDATE products SET name_zh = 'Dalda棕榈油 5升' WHERE id = 175;
UPDATE products SET name_zh = 'Sufi葵花籽油 3升' WHERE id = 176;
UPDATE products SET name_zh = 'Sufi葵花籽油 5升' WHERE id = 177;
UPDATE products SET name_zh = 'Shan菜籽油 3升' WHERE id = 178;
UPDATE products SET name_zh = 'Seasons纯橄榄油 500毫升' WHERE id = 179;
UPDATE products SET name_zh = 'Nutiva椰子油 500毫升' WHERE id = 180;
UPDATE products SET name_zh = 'Zulfi传统酥油 500克' WHERE id = 181;
UPDATE products SET name_zh = 'Phulkari纯酥油 1千克' WHERE id = 182;
UPDATE products SET name_zh = 'Shan尼哈里香料 50克' WHERE id = 183;
UPDATE products SET name_zh = 'Shan卡拉希羊肉香料 50克' WHERE id = 184;
UPDATE products SET name_zh = 'Shan香饭香料 50克' WHERE id = 185;
UPDATE products SET name_zh = 'National咖喱香料 50克' WHERE id = 186;
UPDATE products SET name_zh = 'National烧烤香料 50克' WHERE id = 187;
UPDATE products SET name_zh = 'National番茄酱 500克' WHERE id = 188;
UPDATE products SET name_zh = 'Remia真实蛋黄酱 946毫升' WHERE id = 189;
UPDATE products SET name_zh = 'Rafhan芥末酱 200克' WHERE id = 190;
UPDATE products SET name_zh = '家乐酱油 630毫升' WHERE id = 191;
UPDATE products SET name_zh = 'Shanaz白醋 500毫升' WHERE id = 192;
UPDATE products SET name_zh = 'Ahmed Foods罗望子酱 200克' WHERE id = 193;
UPDATE products SET name_zh = 'National芒果腌菜 1千克' WHERE id = 194;
UPDATE products SET name_zh = 'Guard香米 5千克' WHERE id = 195;
UPDATE products SET name_zh = 'Guard香米 1千克' WHERE id = 196;
UPDATE products SET name_zh = 'Sella蒸谷米 5千克' WHERE id = 197;
UPDATE products SET name_zh = 'Roshan面粉 10千克' WHERE id = 198;
UPDATE products SET name_zh = 'Sooper精制面粉 1千克' WHERE id = 199;
UPDATE products SET name_zh = 'Diamond加碘盐 1千克' WHERE id = 200;
UPDATE products SET name_zh = '鹰嘴豆瓣 500克' WHERE id = 201;
UPDATE products SET name_zh = '黑豆瓣 500克' WHERE id = 202;
UPDATE products SET name_zh = '桂格燕麦 500克' WHERE id = 203;
UPDATE products SET name_zh = 'Shahi细面条 150克' WHERE id = 204;
UPDATE products SET name_zh = 'Rafhan粗面粉 500克' WHERE id = 205;
UPDATE products SET name_zh = '多芬美肤香皂 100克' WHERE id = 206;
UPDATE products SET name_zh = '力士香滑完美香皂 150克' WHERE id = 207;
UPDATE products SET name_zh = '卫宝全效10香皂 125克' WHERE id = 208;
UPDATE products SET name_zh = '舒肤佳家庭护盾香皂 175克' WHERE id = 209;
UPDATE products SET name_zh = '凡士林石油冻 50克' WHERE id = 210;
UPDATE products SET name_zh = '旁氏BB霜 SPF30 18克' WHERE id = 211;
UPDATE products SET name_zh = '玉兰油多效合一面霜 50克' WHERE id = 212;
UPDATE products SET name_zh = '吉列常规剃须泡沫 200毫升' WHERE id = 213;
UPDATE products SET name_zh = '吉列锋速3刀片 4片装' WHERE id = 214;
UPDATE products SET name_zh = 'Lady Speed Stick止汗露 75毫升' WHERE id = 215;
UPDATE products SET name_zh = '斧头黑色诱惑止汗喷雾 150毫升' WHERE id = 216;
UPDATE products SET name_zh = '欧莱雅全面修复精华 40毫升' WHERE id = 217;
UPDATE products SET name_zh = '潘婷全效修护洗发水 360毫升' WHERE id = 218;
UPDATE products SET name_zh = '多芬深层滋养洗发水 360毫升' WHERE id = 219;
UPDATE products SET name_zh = '欧莱雅极致顺滑洗发水 360毫升' WHERE id = 220;
UPDATE products SET name_zh = '清扬冰爽薄荷洗发水 360毫升' WHERE id = 221;
UPDATE products SET name_zh = '多芬深层修护护发素 300毫升' WHERE id = 222;
UPDATE products SET name_zh = '潘婷深度护发素 360毫升' WHERE id = 223;
UPDATE products SET name_zh = '降落伞椰子发油 200毫升' WHERE id = 224;
UPDATE products SET name_zh = 'Jamila指甲花粉 250克' WHERE id = 225;
UPDATE products SET name_zh = '卡尼尔Olia染发剂 60毫升' WHERE id = 226;
UPDATE products SET name_zh = '高露洁极致清新牙膏 150克' WHERE id = 227;
UPDATE products SET name_zh = '洁诺红辣椒牙膏 150克' WHERE id = 228;
UPDATE products SET name_zh = 'Signal美白牙膏 75克' WHERE id = 229;
UPDATE products SET name_zh = '欧乐B交叉动作牙刷' WHERE id = 230;
UPDATE products SET name_zh = '高露洁软毛锯齿牙刷' WHERE id = 231;
UPDATE products SET name_zh = '李施德林全效护理漱口水 500毫升' WHERE id = 232;
UPDATE products SET name_zh = '欧乐B牙线 40米' WHERE id = 233;
UPDATE products SET name_zh = '帮宝适活力婴儿1号 44片' WHERE id = 234;
UPDATE products SET name_zh = '帮宝适婴儿干爽4号 40片' WHERE id = 235;
UPDATE products SET name_zh = '好奇超干爽1号 40片' WHERE id = 236;
UPDATE products SET name_zh = '强生婴儿爽身粉 200克' WHERE id = 237;
UPDATE products SET name_zh = '强生婴儿油 200毫升' WHERE id = 238;
UPDATE products SET name_zh = '雀巢小麦蜂蜜米粉 250克' WHERE id = 239;
UPDATE products SET name_zh = '雀巢能恩1段配方奶粉 400克' WHERE id = 240;
UPDATE products SET name_zh = 'Mamy Poko婴儿湿巾 80片' WHERE id = 241;
UPDATE products SET name_zh = 'Bepanthen尿布疹霜 100克' WHERE id = 242;
UPDATE products SET name_zh = 'Odonil混合花香空气清新剂 75克' WHERE id = 243;
UPDATE products SET name_zh = '空气清新春天清香 300毫升' WHERE id = 244;
UPDATE products SET name_zh = '灭害灵强效防护喷雾 450毫升' WHERE id = 245;
UPDATE products SET name_zh = '雷达飞虫杀虫剂 450毫升' WHERE id = 246;
UPDATE products SET name_zh = '百洁布重型海绵' WHERE id = 247;
UPDATE products SET name_zh = '玫瑰花瓣卫生纸 12卷装' WHERE id = 248;
UPDATE products SET name_zh = '舒洁厨房纸 2卷装' WHERE id = 249;
UPDATE products SET name_zh = '神奇保鲜膜 100米' WHERE id = 250;
UPDATE products SET name_zh = 'Moti铝箔纸 50平方米' WHERE id = 251;
UPDATE products SET name_zh = 'Saaf垃圾袋 30个装' WHERE id = 252;
UPDATE products SET name_zh = 'K&NS鸡肉馅 500克' WHERE id = 253;
UPDATE products SET name_zh = 'K&NS烤肉串 500克' WHERE id = 254;
UPDATE products SET name_zh = 'K&NS鸡肉汉堡饼 6片' WHERE id = 255;
UPDATE products SET name_zh = 'Omore香草冰淇淋 750毫升' WHERE id = 256;
UPDATE products SET name_zh = '和路雪皇家可颂冰淇淋 1升' WHERE id = 257;
UPDATE products SET name_zh = 'Igloo裹粉鱼柳 1千克' WHERE id = 258;
UPDATE products SET name_zh = 'Yummy冷冻芒果酸奶 400克' WHERE id = 259;

COMMIT;

-- Done: 259 products updated